### ISSUE TITLE
centos7 openvas source install error

### ISSUE THREAD

**Issue by ljzlegendice** [greenbone/openvas#349]
###centos7  openvas source install error
when excuting   cmake command , outputing error.
How to resolve it?
-- Configuring the Scanner...
-- Looking for clang-format...
-- clang-format not found...
Set LIBDIR to /usr/local/openvas/lib
-- Install prefix: /usr/local/openvas
-- Checking for module 'libgvm_base>=11.0.0'
--   No package 'libgvm_base' found
CMake Error at /opt/cmake-3.10.2-Linux-x86_64/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/cmake-3.10.2-Linux-x86_64/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  misc/CMakeLists.txt:31 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/tmp/openvas/CMakeFiles/CMakeOutput.log".

**Comment by jjnicola** [comment]
Thanks for your report. Unfortunately this is indeed a wrong channel to report this, because this is not a bug. As far as I can see, you didn't install gvm-libs.
The right channel to ask about this is https://community.greenbone.net/c/gse.
Regards.
