### ISSUE TITLE
Scanning the containers on a host?

### ISSUE THREAD

**Issue by drwetter** [greenbone/openvas#350]
... will that come?

* in terms of misconfiguration
* vulnerabilties

**Comment by bjoernricks** [comment]
Because this isn't and issue with the openvas scanner itself I am closing the ticket. Please use https://community.greenbone.net/ for such questions instead.

**Comment by drwetter** [comment]
Hmm, why is a feature request for additional scanning capabilities for the openvas scanner not the right place?

**Comment by bjoernricks** [comment]
Because this is an issue tracker.

Please use https://community.greenbone.net/ for support questions and feature requests.
