### ISSUE TITLE
pdf reports generated in openvas 8 are damaged.

### ISSUE THREAD

**Issue by sourabhdeshmukh** [greenbone/openvas#356]
I have installed openvas and it is running fine.

When I try to download reports, in xml format they are downloaded and viewed successfully. But when we select pdf reports, it gets downloaded but when we try to open it says reports are damaged.

**Comment by cfi-gb** [comment]
Closing for the following reasons:

1. you already have cross-posted this in https://community.greenbone.net/t/damaged-pdf-reports/2880/
2. The openvas scanner isn't responsible for the generation of PDFs
3. It is more likely a setup issue (missing packages and similar) which should be discussed in the community portal.

**Comment by sourabhdeshmukh** [comment]
Ok closing the issue.
