### ISSUE TITLE
Verification of release assets fails 

### ISSUE THREAD

**Issue by cliffcotino** [greenbone/openvas#359]
I am trying to verify if the released assets for version 6.0.0 have not been modified, using the public key linked to by: https://community.greenbone.net/t/gcf-managing-the-digital-signatures/101

The problem is that both zip and tarball verification fails.
Am I using the correct public key or is something else wrong?

### Expected behavior
Signature verification succeeds 

### Current behavior
Signature verification fails with:

### Steps to reproduce
This is the script I am using:
```
curl -s https://www.greenbone.net/GBCommunitySigningKey.asc -o GBCommunitySigningKey.asc
gpg --import GBCommunitySigningKey.asc

curl -s -L https://github.com/greenbone/openvas/archive/v6.0.0.tar.gz -o source.tar.gz
curl -s -L https://github.com/greenbone/openvas/releases/download/v6.0.0/openvas-scanner-6.0.0.tar.gz.sig -o source.tar.gz.sig
gpg --verify source.tar.gz.sig source.tar.gz

curl -s -L https://github.com/greenbone/openvas/archive/v6.0.0.zip -o source.zip
curl -s -L https://github.com/greenbone/openvas/releases/download/v6.0.0/openvas-scanner-6.0.0.zip.sig -o source.zip.sig
gpg --verify source.zip.sig source.zip
```
Output:
```
gpg: Signature made Fri Apr  5 16:43:13 2019 CEST
gpg:                using RSA key 9823FAA60ED1E580
gpg: BAD signature from "Greenbone Community Feed integrity key" [unknown]
```

The following example for GSA does succeed:
```
curl -s -L https://github.com/greenbone/gsa/archive/v8.0.0.tar.gz -o source.tar.gz
curl -s -L https://github.com/greenbone/gsa/releases/download/v8.0.0/gsa-8.0.0.tar.gz.sig -o source.tar.gz.sig
gpg --verify source.tar.gz.sig source.tar.gz
```

### GVM versions
**gsa: 8.0.0**
**gvm: 8.0.0**
**openvas-scanner: 6.0.0**
**gvm-libs: 10.0.0**
**openvas-smb:**

### Environment
**Operating system: MacOS**
**Installation method / source: source installation**

### Logfiles
```
gpg: Signature made Fri Apr  5 16:43:13 2019 CEST
gpg:                using RSA key 9823FAA60ED1E580
gpg: BAD signature from "Greenbone Community Feed integrity key" [unknown]
```

**Comment by jjnicola** [comment]
Hi @cliffcotino,
thanks for report this issue. New signature files were uploaded for the .zip and .tar.gz file. Please feel free to close the issue if it works for you now.
Regards.

**Comment by cliffcotino** [comment]
The new signature files are indeed correct.

If I'm not mistaken I verified the tarballs using the signatures successfully for v6.0.0 in April/May.
Were the tarballs updated in the meantime or am I mistaken?

**Comment by jjnicola** [comment]
Hi @cliffcotino
We change the repository name some weeks ago. Since a release tarball is made automatically by Github, and it prepends the repository name to each file in the archive as prefix, this is the single change (non intentional) in the tarball, and the reason for which the signatures were not correct anymore. The tag is the same and it points to the same commit as before.
Thanks again for reporting this issue.
Regards

**Comment by cliffcotino** [comment]
Okay, that explains the issue then.
Thanks for uploading the new signatures!
