### ISSUE TITLE
openvas-scanner.service is not a native service, redirecting to systemd-sysv-install

### ISSUE THREAD

**Issue by arjunpalex** [greenbone/openvas#366]
Hi, I am Arjun. I am very new to Linux Platform and i have installed OpenVAS on Ubuntu 18.04.2 OS. Getting the below message when i try to enable the service for auto start while rebooting the machine. 

systemctl enable openvas-scanner/manager/gsa

openvas-scanner.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvas-scanner

I tried some work around as i found on google but no luck.

Kindly help me on this.

Thanks & Regards
Arjun

**Comment by cfi-gb** [comment]
Hi,

i'm closing this issue as invalid because this is a bugtracker for the "openvas" tool and no support forum for general Linux topics / questions.

I would suggest to ask such a question at e.g. https://ubuntuforums.org/
