### ISSUE TITLE
Feature Request: Upload signing keys to keyserver

### ISSUE THREAD

**Issue by shibumi** [greenbone/openvas#368]
Hi,
I am desperately looking for your signing public key. Where do I find: `9823FAA60ED1E580`. It would help so much, if you can upload all your signing keys to keyservers.. Right now I need to dig through the whole internet when you change a key and can't find it, because you seem to announce such keys in forum posts:

https://community.greenbone.net/t/gcf-managing-the-digital-signatures/101

**Comment by shibumi** [comment]
Ok, found it: https://community.greenbone.net/t/greenbone-community-feed-change-of-signature-key-dec-1st-2018/417

Could you please, please link the key in your project Readmes or put them on a central website or upload them via gpg to a key server? This would help so much.

**Comment by bjoernricks** [comment]
@shibumi does this fit for you https://github.com/greenbone/gsa/pull/1559 ?

**Comment by shibumi** [comment]
@bjoernricks if you use the same key for all your projects.. yes. But I have another wish. Please build a chain of trust when you release a new signing key. I see that you have replaced your signing key in december 2018 with a new one, and you didn't sign it with the old one. Therefore  it's not really trustable. So if you plan to release a new signing key in the future, please sign it with the old one, so we can make sure that the new signing key is really yours.

**Comment by bjoernricks** [comment]
@shibumi yes we are using the same key for all release files. This is our only key for signing stuff. To be precise I am going to add this section to all readme files of all our repos.
