### ISSUE TITLE
Latest stable GVM dont find vulnerabilities

### ISSUE THREAD

**Issue by japroc** [greenbone/openvas#375]
Hello!

I have the host in my network, which is specially configured to be vulnerable to EthernalBlue (MS17-010). Thereby plugin Microsoft Windows SMB Server Multiple Vulnerabilities-Remote (4013389) should find this issue.

I use last stable versions. gsad 8.0.1.  gvmd 8.0.1. openvassd 6.0.1. gvm-libs 10.0.1. 
Also i compare results with version 9. https://github.com/mikesplain/openvas-docker

So i scan with `full and very deep ultimate` scan config. And my GVM-10 finds only mediocre staff like os detection, ping, hostname (severity = 0). Meanwhile GVM-9 finds MS17-010 with appropriate remote check nvt plugin.

MS17-010 is an example. Scan result differ a lot at all.

There are no any special information in log files. What may i do wrong?

### Environment
**Installation method / source:** (packages, source installation)
Build from release tar.gz archives inside Dockerfile from debian:9.5
Btw, i build with postgres backend
```

```

### Logfiles
```
root@c80371f6d3c0:/openvas# cat /usr/local/var/log/gvm/openvassd.log 
sd   main:MESSAGE:2019-08-27 14h48.20 utc:1453: openvassd 6.0.1 started
sd   main:MESSAGE:2019-08-27 15h04.37 utc:10267: Starts a new scan. Target(s) : <ipv6_addr>, <ipv4_addr>, with max_hosts = 20 and max_checks = 4
sd   main:MESSAGE:2019-08-27 15h04.37 utc:10466: Testing <ipv6_addr> (Vhosts: <host2>) [10466]
lib  misc:MESSAGE:2019-08-27 15h04.37 utc:10471: Failed to find interface lo mentioned in /proc/net/route
lib  misc:MESSAGE:2019-08-27 15h04.37 utc:10471: Failed to find interface lo mentioned in /proc/net/route
sd   main:MESSAGE:2019-08-27 15h04.38 utc:10573: Testing <ipv4_addr> (Vhosts: <host2>) [10573]
lib  misc:MESSAGE:2019-08-27 15h04.49 utc:13609: Failed to find interface lo mentioned in /proc/net/route
lib  misc:MESSAGE:2019-08-27 15h04.49 utc:13609: Failed to find interface lo mentioned in /proc/net/route
lib  misc:MESSAGE:2019-08-27 15h05.07 utc:15861: Failed to find interface lo mentioned in /proc/net/route
lib  misc:MESSAGE:2019-08-27 15h05.07 utc:15861: Failed to find interface lo mentioned in /proc/net/route
sd   main:MESSAGE:2019-08-27 15h05.08 utc:10466: Finished testing <ipv6_addr>. Time : 30.50 secs
sd   main:MESSAGE:2019-08-27 15h05.50 utc:10573: Finished testing <ipv4_addr>. Time : 72.00 secs
sd   main:MESSAGE:2019-08-27 15h05.50 utc:10267: Test complete
sd   main:MESSAGE:2019-08-27 15h05.50 utc:10267: Total time to scan all hosts : 75 seconds
```

**Comment by bjoernricks** [comment]
Hi,

did you take a look at https://community.greenbone.net/ already? IIRC there are several topics about this issue. Otherwise please report your problem at the GSE category https://community.greenbone.net/c/gse
We are using this issue tracker for problems with the source code. Your question is more usage related.

**Comment by japroc** [comment]
Oh, thank you. Did not find the answer. So i created new issue.

I guess is to be closed
