### ISSUE TITLE
Issues on kali 2020

### ISSUE THREAD

**Issue by Norup123** [greenbone/openvas#454]
I just installed openvas on my new kali release and are having some issues with it. When i access the web admin page it gives me the warning SecInfo Database Missing. I have tried the openvas-feed-update and it runs without complaining but it doesnt really download anything
When i run openvas-start i get the following
`kali@kali:~$ sudo openvas-start 
[i] Something is already using port: 9392/tcp
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gsad    1795 root    6u  IPv4  28289      0t0  TCP localhost:9392 (LISTEN)

UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root        1795       1  0 07:03 ?        SLsl   0:23 /usr/sbin/gsad --foreground --listen=127.0.0.1 --por

[*] Please wait for the OpenVAS services to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI (Greenbone Security Assistant): https://127.0.0.1:9392

● greenbone-security-assistant.service - Greenbone Security Assistant
     Loaded: loaded (/lib/systemd/system/greenbone-security-assistant.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2020-02-20 07:04:00 EST; 50min ago
       Docs: man:gsad(8)
             http://www.openvas.org/
   Main PID: 1795 (gsad)
      Tasks: 10 (limit: 4660)
     Memory: 366.6M
     CGroup: /system.slice/greenbone-security-assistant.service
             ├─1795 /usr/sbin/gsad --foreground --listen=127.0.0.1 --port=9392 --mlisten=127.0.0.1 --mport=9390
             └─1804 /usr/sbin/gsad --foreground --listen=127.0.0.1 --port=9392 --mlisten=127.0.0.1 --mport=9390

Feb 20 07:46:35 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:36 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:41 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:42 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:48 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:50 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.

● openvas-scanner.service - Open Vulnerability Assessment System Scanner Daemon
     Loaded: loaded (/lib/systemd/system/openvas-scanner.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2020-02-20 07:05:00 EST; 49min ago
       Docs: man:openvassd(8)
             http://www.openvas.org/
   Main PID: 1823 (openvassd)
      Tasks: 1 (limit: 4660)
     Memory: 45.5M
     CGroup: /system.slice/openvas-scanner.service
             └─1823 openvassd: Waiting for incoming connections

Feb 20 07:46:35 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:36 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:41 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:42 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:48 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:50 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.

● openvas-manager.service - Open Vulnerability Assessment System Manager Daemon
     Loaded: loaded (/lib/systemd/system/openvas-manager.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2020-02-20 07:04:00 EST; 50min ago
       Docs: man:openvasmd(8)
             http://www.openvas.org/
   Main PID: 1798 (openvasmd)
      Tasks: 1 (limit: 4660)
     Memory: 81.6M
     CGroup: /system.slice/openvas-manager.service
             └─1798 openvasmd

Feb 20 07:46:35 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:36 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:41 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:42 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:48 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:50 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.

[*] Opening Web UI (https://127.0.0.1:9392) in: 5... 4... 3... 2... 1...`

Not sure what to do about this

**Comment by Norup123** [comment]
The openvas-check-setup gives the following

`kali@kali:~$ sudo openvas-start 
[i] Something is already using port: 9392/tcp
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gsad    1795 root    6u  IPv4  28289      0t0  TCP localhost:9392 (LISTEN)

UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root        1795       1  0 07:03 ?        SLsl   0:23 /usr/sbin/gsad --foreground --listen=127.0.0.1 --por

[*] Please wait for the OpenVAS services to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI (Greenbone Security Assistant): https://127.0.0.1:9392

● greenbone-security-assistant.service - Greenbone Security Assistant
     Loaded: loaded (/lib/systemd/system/greenbone-security-assistant.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2020-02-20 07:04:00 EST; 50min ago
       Docs: man:gsad(8)
             http://www.openvas.org/
   Main PID: 1795 (gsad)
      Tasks: 10 (limit: 4660)
     Memory: 366.6M
     CGroup: /system.slice/greenbone-security-assistant.service
             ├─1795 /usr/sbin/gsad --foreground --listen=127.0.0.1 --port=9392 --mlisten=127.0.0.1 --mport=9390
             └─1804 /usr/sbin/gsad --foreground --listen=127.0.0.1 --port=9392 --mlisten=127.0.0.1 --mport=9390

Feb 20 07:46:35 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:36 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:41 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:42 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:48 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.
Feb 20 07:46:50 kali systemd[1]: /lib/systemd/system/greenbone-security-assistant.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/gsad.pid → /run/gsad.pid; please update the unit file accordingly.

● openvas-scanner.service - Open Vulnerability Assessment System Scanner Daemon
     Loaded: loaded (/lib/systemd/system/openvas-scanner.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2020-02-20 07:05:00 EST; 49min ago
       Docs: man:openvassd(8)
             http://www.openvas.org/
   Main PID: 1823 (openvassd)
      Tasks: 1 (limit: 4660)
     Memory: 45.5M
     CGroup: /system.slice/openvas-scanner.service
             └─1823 openvassd: Waiting for incoming connections

Feb 20 07:46:35 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:36 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:41 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:42 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:48 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.
Feb 20 07:46:50 kali systemd[1]: /lib/systemd/system/openvas-scanner.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvassd.pid → /run/openvassd.pid; please update the unit file accordingly.

● openvas-manager.service - Open Vulnerability Assessment System Manager Daemon
     Loaded: loaded (/lib/systemd/system/openvas-manager.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2020-02-20 07:04:00 EST; 50min ago
       Docs: man:openvasmd(8)
             http://www.openvas.org/
   Main PID: 1798 (openvasmd)
      Tasks: 1 (limit: 4660)
     Memory: 81.6M
     CGroup: /system.slice/openvas-manager.service
             └─1798 openvasmd

Feb 20 07:46:35 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:36 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:38 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:41 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:42 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:46 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:48 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.
Feb 20 07:46:50 kali systemd[1]: /lib/systemd/system/openvas-manager.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvasmd.pid → /run/openvasmd.pid; please update the unit file accordingly.

[*] Opening Web UI (https://127.0.0.1:9392) in: 5... 4... 3... 2... 1...`

**Comment by Norup123** [comment]
the openvas-check-setup gives the following:

`openvas-check-setup 2.3.7
  Test completeness and readiness of OpenVAS-9
  (add '--v6' or '--v7' or '--v8'
   if you want to check for another OpenVAS version)

  Please report us any non-detected problems and
  help us to improve this check routine:
  http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss

  Send us the log-file (/tmp/openvas-check-setup.log) to help analyze the problem.

  Use the parameter --server to skip checks for client tools
  like GSD and OpenVAS-CLI.

Step 1: Checking OpenVAS Scanner ... 
        OK: OpenVAS Scanner is present in version 5.1.3.
        OK: redis-server is present in version v=5.0.7.
        OK: scanner (kb_location setting) is configured properly using the redis-server socket: /var/run/redis-openvas/redis-server.sock
        OK: redis-server is running and listening on socket: /var/run/redis-openvas/redis-server.sock.
        OK: redis-server configuration is OK and redis-server is running.
        OK: NVT collection in /var/lib/openvas/plugins contains 57783 NVTs.
        WARNING: Signature checking of NVTs is not enabled in OpenVAS Scanner.
        SUGGEST: Enable signature checking (see http://www.openvas.org/trusted-nvts.html).
        WARNING: The initial NVT cache has not yet been generated.
        SUGGEST: Start OpenVAS Scanner for the first time to generate the cache.
Step 2: Checking OpenVAS Manager ... 
        OK: OpenVAS Manager is present in version 7.0.3.
        OK: OpenVAS Manager database found in /var/lib/openvas/mgr/tasks.db.
        OK: Access rights for the OpenVAS Manager database are correct.
        OK: sqlite3 found, extended checks of the OpenVAS Manager installation enabled.
        OK: OpenVAS Manager database is at revision 184.
        OK: OpenVAS Manager expects database at revision 184.
        OK: Database schema is up to date.
        OK: OpenVAS Manager database contains information about 57783 NVTs.
        OK: At least one user exists.
        ERROR: No OpenVAS SCAP database found. (Tried: /var/lib/openvas/scap-data/scap.db)
        FIX: Run a SCAP synchronization script like greenbone-scapdata-sync.

 ERROR: Your OpenVAS-9 installation is not yet complete!

Please follow the instructions marked with FIX above and run this
script again.

If you think this result is wrong, please report your observation
and help us to improve this check routine:
http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss
Please attach the log-file (/tmp/openvas-check-setup.log) to help us analyze the problem.`

**Comment by jjnicola** [comment]
Hi @Norup123,
Unfortunately this is the wrong channel to ask this, because this is not a bug.
The right channel to ask about this is https://community.greenbone.net/c/gse.

**Comment by azamet90** [comment]
> Hi @Norup123,
> Unfortunately this is the wrong channel to ask this, because this is not a bug.
> The right channel to ask about this is https://community.greenbone.net/c/gse.

this is not a bug but happen same to me :-/

**Comment by LinuxlinkedBD** [comment]
i am facing the same issue:
![image](https://user-images.githubusercontent.com/70909031/111514100-9e360680-877b-11eb-853e-ad599bd68da0.png)

also i am not able to sync the feed
amin@cli:~$ sudo greenbone-nvt-sync
[sudo] password for amin: 
--2021-03-17 22:23:36--  http://dl.greenbone.net/community-nvt-feed-current.tar.bz2
Resolving dl.greenbone.net (dl.greenbone.net)... 89.146.224.58, 2a01:130:2000:127::d1
Connecting to dl.greenbone.net (dl.greenbone.net)|89.146.224.58|:80... failed: Connection timed out.
Connecting to dl.greenbone.net (dl.greenbone.net)|2a01:130:2000:127::d1|:80... failed: Network is unreachable.
amin@cli:~$ sudo greenbone-scapdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
amin@cli:~$ sudo greenbone-certdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
