### ISSUE TITLE
could not get  size of file from preference

### ISSUE THREAD

**Issue by huifeidexingyuner** [greenbone/openvas#464]
sd   main:MESSAGE:2020-03-19 06h37.54 utc:62123: openvas 7.0.0 started
sd   main:MESSAGE:2020-03-19 06h38.02 utc:62123: Starts a new scan. Target(s) : 172.31.5.88, with max_hosts = 30 and max_checks = 10
sd   main:MESSAGE:2020-03-19 06h38.03 utc:62170: Testing 172.31.5.88 [62170]
lib  nasl:MESSAGE:2020-03-19 06h38.05 utc:62228: [62228](/usr/local/var/lib/openvas/plugins/gb_default_credentials_options.nasl:92) script_get_preference_file_content: could not get  size of file from preference Credentials file:
lib  nasl:MESSAGE:2020-03-19 06h39.15 utc:65494: [65494](/usr/local/var/lib/openvas/plugins/Policy/gb_policy_cpe.nasl:65) script_get_preference_file_content: could not get  size of file from preference CPE List

These are the errors reported in  /usr/local/var/log/gvm/openvas.log，Is it because of a lack of configuration？

**Comment by huifeidexingyuner** [comment]
openvas version is:
OpenVAS 7.0.0
Most new code since 2005: (C) 2019 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by jjnicola** [comment]
Solved with PR #409. This patch will be included In the next stable release.

**Comment by karkaaa** [comment]
maybe it is possible workaround?
