### ISSUE TITLE
HTTP Feed not working / wrong URL?

### ISSUE THREAD

**Issue by kaistierl** [greenbone/openvas#476]
### Expected behavior

`/usr/sbin/greenbone-nvt-sync --wget` downloads the current NVT feed

### Actual behavior

The downloaded file is corrupt / not the feed but the greenbone homepage...

```
Start refreshing NVTs...
Setting http_proxy and https_proxy environment variables
Syncing NVTs using wget
--2020-04-09 21:42:55--  http://dl.greenbone.net/community-nvt-feed-current.tar.bz2
Connecting to 192.168.0.100:3128... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: http://www.greenbone.net [following]
--2020-04-09 21:42:55--  http://www.greenbone.net/
Reusing existing connection to 192.168.0.100:3128.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://www.greenbone.net/ [following]
--2020-04-09 21:42:55--  https://www.greenbone.net/
Connecting to 192.168.0.100:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 97000 (95K) [text/html]
Saving to: '/tmp/greenbone-nvt-sync.9AbY8yQIRJ/openvas-feed-2020-04-09-167.tar.bz2'

100%[========================================================================================================================================================================>] 97,000      --.-K/s   in 0.04s

2020-04-09 21:42:56 (2.13 MB/s) - '/tmp/greenbone-nvt-sync.9AbY8yQIRJ/openvas-feed-2020-04-09-167.tar.bz2' saved [97000/97000]

bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

### Steps to reproduce

simply run `/usr/sbin/greenbone-nvt-sync --wget`

Or: Try downloading http://dl.greenbone.net/community-nvt-feed-current.tar.bz2 using curl or a browser. This gets redirected to the greenbone homepage.

URL is the current one given in https://github.com/greenbone/openvas/blob/master/tools/greenbone-nvt-sync.in

**Comment by kaistierl** [comment]
...unfortunately this is blocking a production environment for me since we cannot get the feed via rsync due to proxy issues...

**Comment by AlanKellyEire** [comment]
Also encountering the same issue.

**Comment by cfi-gb** [comment]
Thanks for your report.

This is a problem with the feed services and not originating from the OpenVAS scanner so closing this issue as invalid for this repository.

Please use https://community.greenbone.net/t/community-feed-url-redirects-to-greenbone-net-nvt-sync-fails/4887 for further discussions.

**Comment by silverark** [comment]
@cfi-gb  Moderators saying that we should be using rsync (which still works) rather than http on the link you have provided. But this script specifically forces http for the first sync when there is no database. This will kill most installation unless you manually edit the script. Looks like Greenbone know the http version isn't working. Does this mean the script needs to change to rsync only?

**Comment by NitinBhasneria** [comment]
@cfi-gb @silverark after this I am encountered with error
`The number of NVTs in the OpenVAS Manager database is too low.` Even the openvasmd --rebuild do not work. Please guide

**Comment by cfi-gb** [comment]
@NitinBhasneria from the issue template:

> 1. Be aware that this is not a support forum. If your issue is rather a question than a bug report, please use our community forum at https://community.greenbone.net/c/gse instead.

Please follow this advice.

**Comment by cfi-gb** [comment]
@silverark It seems the HTTP based download options are now completely dropped in favor of rsync: https://github.com/greenbone/openvas/pull/478

**Comment by rakibulinux** [comment]
The problem fixed. Use this: 

> greenbone-nvt-sync --rsync or sudo greenbone-nvt-sync --rsync

**Comment by silverark** [comment]
Hi all, thanks for the update. I've already mentioned above that the rsync works and it looks like greenbone are dropping the http/https. I think this issue should be reopened to address the changes that are needed to the greenbone-nvt-sync as by default it falls back to the http version for the initial sync. If it's official the http version isn't coming back, it makes sense to remove it from the script. 

I'm happy to make the changes if everyone agrees that's the best course of action.

https://github.com/greenbone/openvas/blob/e19bd4e657ddfcee678c4241e818aa8bf02584e2/tools/greenbone-nvt-sync.in#L481

**Comment by cfi-gb** [comment]
> @silverark It seems the HTTP based download options are now completely dropped in favor of rsync: #478

Official announcement: https://community.greenbone.net/t/shutting-down-gcf-http-download/5339
