### ISSUE TITLE
Does the openvas scanner support IPv6 network?

### ISSUE THREAD

**Issue by yldiscover** [greenbone/openvas#506]
Does the openvas scanner support IPv6 network?

**Comment by ArnoStiefvater** [comment]
This is a support question not a report of a bug in our openvas scanner. Therefore I am closing this issue. 
To answer your question, yes, openvas scanner supports IPv6.
In the future you can can either read the documentation (https://docs.greenbone.net/GSM-Manual/gos-6/en/scanning.html) or raise a question at our community forum at https://community.greenbone.net/c/gse/16.
