### ISSUE TITLE
openvas: error while loading shared libraries: libopenvas_nasl.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by herdiansah571** [greenbone/openvas#514]
hello,

I try install & compile openvas-7.0.1. then i run command greenbone-nvt-sync and the ouputs like bellow:

          3,320 100%    2.57kB/s    0:00:01 (xfr#7131, ir-chk=7913/15067)
2011/gb_adobe_fms_49103.nasl
          3,425 100%    2.65kB/s    0:00:01 (xfr#7132, ir-chk=7912/15067)
2011/gb_adobe_fms_dos_vuln_aug11.nasl
          3,455 100%    2.67kB/s    0:00:01 (xfr#7133, ir-chk=7911/15067)
2011/gb_adobe_fms_xml_data_dos_vuln.nasl
          3,417 100%    2.34kB/s    0:00:01 (xfr#7134, ir-chk=7910/15067)
2011/gb_adobe_prdts_code_execution_vuln_apr11_win.nasl
          4,508 100%    3.08kB/s    0:00:01 (xfr#7135, ir-chk=7909/15067)
2011/gb_adobe_prdts_cooltype_mem_crptn_vuln_win.nasl
          4,379 100%    2.99kB/s    0:00:01 (xfr#7136, ir-chk=7908/15067)
2011/gb_adobe_prdts_mult_bof_vuln_jun11_win.nasl
          4,160 100%    2.82kB/s    0:00:01 (xfr#7137, ir-chk=7907/15067)
2011/gb_adobe_prdts_mult_vuln_feb11_win.nasl
          4,610 100%    3.11kB/s    0:00:01 (xfr#7138, ir-chk=7906/15067)
2011/gb_adobe_prdts_mult_vuln_sep11_macosx.nasl
          4,329 100%    2.92kB/s    0:00:01 (xfr#7139, ir-chk=7905/15067)
2011/gb_adobe_prdts_mult_vuln_sep11_win.nasl
          3,981 100%    3.80MB/s    0:00:00 (xfr#7140, ir-chk=7904/15067)
2011/gb_adobe_prdts_u3d_mem_crptn_vuln_macosx.nasl
          3,911 100%    3.73MB/s    0:00:00 (xfr#7141, ir-chk=7903/15067)
2011/gb_adobe_prdts_u3d_mem_crptn_vuln_win.nasl
          3,828 100%  934.57kB/s    0:00:00 (xfr#7142, ir-chk=7902/15067)
2011/gb_adobe_prdts_xss_vuln_win_jun11.nasl
          4,122 100%  670.90kB/s    0:00:00 (xfr#7143, ir-chk=7901/15067)
2011/gb_adobe_reader_mult_vuln_feb11_lin.nasl
          4,035 100%  218.91kB/s    0:00:00 (xfr#7144, ir-chk=7900/15067)
2011/gb_adobe_reader_mult_vuln_sep11_lin.nasl
          3,453 100%  153.28kB/s    0:00:00 (xfr#7145, ir-chk=7899/15067)
2011/gb_adobe_reader_u3d_mem_crptn_vuln_lin.nasl
          3,310 100%  134.68kB/s    0:00:00 (xfr#7146, ir-chk=7898/15067)
2011/gb_adobe_reader_unspecified_vuln_win.nasl
          3,139 100%  113.53kB/s    0:00:00 (xfr#7147, ir-chk=7897/15067)
2011/gb_adobe_shockwave_player_mult_code_exec_vuln_feb11.nasl
          3,859 100%  125.62kB/s    0:00:00 (xfr#7148, ir-chk=7896/15067)
2011/gb_adobe_shockwave_player_mult_unspecified_vuln.nasl
          3,715 100%  113.37kB/s    0:00:00 (xfr#7149, ir-chk=7895/15067)
2011/gb_adobe_shockwave_player_mult_vuln_nov11_macosx.nasl
          3,291 100%   48.69kB/s    0:00:00 (xfr#7150, ir-chk=7894/15067)
2011/gb_adobe_shockwave_player_mult_vuln_nov11_win.nasl
rsync: read error: Connection reset by peer (104)
rsync error: error in socket IO (code 10) at io.c(785) [receiver=3.1.3]
rsync: connection unexpectedly closed (744114 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [generator=3.1.3]

then I run openvas --update-vt-info and the outputs like bellow :
[gvm@centos-8 gvm]$ openvas --update-vt-info
openvas: error while loading shared libraries: libopenvas_nasl.so.11: cannot open shared object file: No such file or directory

anyone can help me to fix this issue ?
I follow this url https://community.greenbone.net/t/full-gvm-11-build-guide-for-centos-8/5425 for install gvm 11 on centos 8

regards,
Herdiansah

**Comment by cfi-gb** [comment]
This is a setup / installation issue so i'm closing it as invalid. Please follow the advice given in the issue template:

> Before reporting an issue please:
>
> 1. Be aware that this is not a support forum. If your issue is rather a question
>   than a bug report, please use our community forum at
>   https://community.greenbone.net/c/gse instead.
