### ISSUE TITLE
community feed

### ISSUE THREAD

**Issue by rgfhfdghfgdh435645365** [greenbone/openvas#515]
https://www.greenbone.net/GBCommunitySigningKey.asc 

Failed to decode the given file with current community version.

**Comment by bjoernricks** [comment]
I don't get what you are trying to report. Could you write a detailed description and maybe a question?

**Comment by rgfhfdghfgdh435645365** [comment]
IT was a DNS issue why the community feed was not downloading. I thought it was due to the key missing, so I tried uploading the key at that link. When uploaded via http it would say it couldn't decode it. Its probably a non-issue at this point.

**Comment by cfi-gb** [comment]
For the records:

The GBCommunitySigningKey.asc is a signing key which is completely different from the GSF / GCF access key and it seems you have tried to use the signing key for the HTTP upload of the access key.

This is indeed a non-issue, at least for this repository.
