### ISSUE TITLE
update to new, now  scheduler: 1.3.6.1.4.1.25623.1.0.811246 depends on oracle_webLogic_server_detect.nasl which could not be found

### ISSUE THREAD

**Issue by hktalent** [greenbone/openvas#529]
update to new, now  scheduler: 1.3.6.1.4.1.25623.1.0.811246 depends on oracle_webLogic_server_detect.nasl which could not be found
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/18223385/84661859-8829ba00-af4d-11ea-8ebb-98cffc9cb5a2.png">
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/18223385/84661927-a2639800-af4d-11ea-87b2-c1f49b9c0399.png">

**Comment by hktalent** [comment]
in docker openvas9
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/18223385/84718799-37957980-afac-11ea-87da-1d5bda6f95e7.png">

**Comment by hktalent** [comment]
cat openvassd.messages
<img width="839" alt="image" src="https://user-images.githubusercontent.com/18223385/84719329-a921f780-afad-11ea-84e7-13ba5b8e6827.png">

**Comment by jjnicola** [comment]
This does not seems to be a bug, but a setup / installation issue. Please follow the advice given in the issue template and use the [community forum](https://community.greenbone.net/c/gse/16) instead.
