### ISSUE TITLE
Outdated Reports

### ISSUE THREAD

**Issue by mrod23** [greenbone/openvas#531]
I'm seeing the below in the summary of newly scanned reports:

Report outdated Scan Engine / Environment (local)

**Comment by jjnicola** [comment]
Hi @mrod23, 
could you please add more information ? 
When you create a new issue in the bug tracker there is a template to fill with information, which is useful for debugging.

**Comment by cfi-gb** [comment]
See:

https://community.greenbone.net/t/frequently-asked-questions-faq/5558#heading--outdated-components

-> Close.
