### ISSUE TITLE
error: too few arguments to function ‘pcap_findalldevs’ iface = pcap_findalldevs();

### ISSUE THREAD

**Issue by mkula111** [greenbone/openvas#595]
I don't remember how to program in C, but I keep getting this error when I try to "make"  the openvas package.  The cmake works ok but I run into errors when trying to make and make install.  I.E. error: too few arguments to function ‘pcap_findalldevs’
   69 |     iface = pcap_findalldevs();
I don't know what arguments are needed and I've searched the internet, but  nobody is up to date on this.  I've tried some things but I don't know the solution.   I don't know what the required arguments must be for pcap_findalldevs.  Please help me.  I run Kali linux and cmake version 3.16.3

### Steps to reproduce

1.
2.
3.

### GVM versions

**gsa:** (gsad --version)

**gvm:** (gvmd --version)

**openvas:** (openvas --version)

**gvm-libs:**

**openvas-smb:**

**ospd-openvas:** (ospd-openvas --version)

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```
```

**Comment by jjnicola** [comment]
Duplicated of Issue #511
