### ISSUE TITLE
README.md: link to Greenbone Community Edition broken

### ISSUE THREAD

**Issue by hreese** [greenbone/openvas#616]
### Expected behavior

Find Greenbone Community Edition when clicking on https://www.greenbone.net/en/community-edition/

### Actual behavior

Got 404.

### Steps to reproduce

1. Open README.md
2. Click on https://www.greenbone.net/en/community-edition/

### GVM versions / env / logs

Does not apply.

### Potential solution

I could not find any resources for the Greenbone Community Edition. If it still exists fix the link. If not just remove the third paragraph in README.md.

**Comment by jjnicola** [comment]
Hi  @hreese,
Thanks for reporting the broken link. I will fix this soon.
Greenbone Community Edition was renamed to  Greenbone Security Manager TRIAL (GSM TRIAL). You can find it in the Greenbone Community Portal [here](https://community.greenbone.net/t/setting-up-the-greenbone-security-manager-trial-gsm-trial-virtual-machine/6939).
Regards.

**Comment by cfi-gb** [comment]
All done in #617, https://github.com/greenbone/gvmd/pull/1338, https://github.com/greenbone/gsa/pull/2538, https://github.com/greenbone/gvm-libs/pull/418 and https://github.com/greenbone/openvas-smb/pull/28.

Thanks again for reporting this.
