### ISSUE TITLE
Installing from GIT on Arch Linux

### ISSUE THREAD

**Issue by ChromeSilver** [greenbone/openvas#619]
Hi Team, I tried several times now to install OpenVAS on Arch Linux after cloning from GIT:

1. I installed GVM-Libs without any problems
2. I tried installing gvm-libs like described in INSTALL.md, but cmake breaks with error that it doesn't find required package:

---snip---
-- Checking for module 'libgvm_base>=21.04'
--   Package 'libgvm_base', required by 'virtual:world', not found
CMake Error at /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  src/CMakeLists.txt:29 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
---snip---

# echo $PKG_CONFIG_PATH
/usr/lib/pkgconfig/

# echo $PATH
/usr/lib/pkgconfig/:/usr/local/lib/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

# ls -lha /usr/lib/pkgconfig                                                                     
insgesamt 3,2M                                                                                                         
drwxr-xr-x   2 root root  36K  8. Nov 09:52 .                                                                          
drwxr-xr-x 150 root root 132K  8. Nov 09:52 ..                                                                         
-rw-r--r--   1 root root  275 21. Okt 16:16 alsa.pc                                                                    
-rw-r--r--   1 root root  150 21. Okt 16:16 alsa-topology.pc 
---snip--

Would you please help me out?

Cheers,
ChromeSilver

**Comment by cfi-gb** [comment]
Please note that this is an issue tracker for tracking / handling bugreports. For setup / install / configuration help please use https://community.greenbone.net, thanks for helping to keep the community channels clean.

Nevertheless a short hint:

You probably haven't configured the `LD_LIBRARY_PATH` correctly and thus libgvm isn't found.
