### ISSUE TITLE
Installer guide for Centos7

### ISSUE THREAD

**Issue by C1ph3R-s** [greenbone/openvas#640]
hi,

I would like to install greenbone on Centos7, but unfortunately available guides not very exact.
I have used this: https://bobcares.com/blog/install-openvas-centos-7/

So, could you give me a guide or installer script for centos 7?

The main problem is:

```
Error: Package: OSPd-openvas-1.0.0-9460.el7.art.noarch (atomic)
           Requires: python36-defusedxml
Error: Package: OSPd-2.0.0-9459.el7.art.noarch (atomic)
           Requires: python36-defusedxml
Error: Package: OSPd-openvas-1.0.0-9460.el7.art.noarch (atomic)
           Requires: python36-paramiko
Error: Package: OSPd-2.0.0-9459.el7.art.noarch (atomic)
           Requires: python36-paramiko
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Thanks

**Comment by y0urself** [comment]
You might look in our [community forum](https://community.greenbone.net/). This page is for issues not for questions like this. Thanks.
